[ONBOARDING] Basic Navigation
cuappdev/uplift-android pull request #62
Opened 2024-10-17 20:49 UTC by vstarzf

Adds basic navigation between onboarding screens
- "Login" button in the sign in screen navigates to the profile creation screen (placeholder to demonstrate behavior of successful login)
- "Skip" button in the sign in screen navigates directly to the home screen (bypasses remainder of onboarding)
- Get started button in profile creation screen navigates to the home screen (completes onboarding)
- Bottom nav bar doesn't display during onboarding flow

2024-10-19 22:51 UTC, AndrewCheung360 commented
![image](https://github.com/user-attachments/assets/8d19ebd8-d31a-45d2-988c-081290fc227d)
For the profile creation screen with the checkmarks, I think the current background is pinkish, so we might need to change background color. Also, it might be because of my emulator, but I think part of the "Complete your profile" title gets covered by the camera; not too sure how to fix though.

2024-10-19 22:54 UTC, AndrewCheung360 commented on app/src/main/java/com/cornellappdev/uplift/ui/screens/SignInPromptScreen.kt
>      Button(
I think the login button is a little wider with larger border radius on the figma

2024-10-19 22:56 UTC, AndrewCheung360 commented on app/src/main/java/com/cornellappdev/uplift/ui/screens/SignInPromptScreen.kt
>  @OptIn(ExperimentalPermissionsApi::class)
Android Studio is telling me that this is not needed

2024-10-19 22:57 UTC, AndrewCheung360 commented on app/src/main/java/com/cornellappdev/uplift/ui/screens/SignInPromptScreen.kt
>  import androidx.compose.material3.CardElevation
Some imports are unused

2024-10-19 22:57 UTC, AndrewCheung360 commented on app/src/main/java/com/cornellappdev/uplift/ui/screens/ProfileCreationScreen.kt
>  import androidx.compose.material3.Scaffold
some imports are unused

2024-10-19 23:05 UTC, AndrewCheung360 commented
For the Elevated Card items in UpliftUsesCardList(), I think you can extract them into a composable that takes in text and a painterResource for more reusability, and I think for the shadow effect you can make use of the elevation property of ElevatedCard instead of creating the shadows manually in Modifier. 

![image](https://github.com/user-attachments/assets/4d0dc34a-e209-465c-afdf-cae44f391a57)

2024-10-19 23:07 UTC, AndrewCheung360 requested changes
The onboarding navigation looks great, and works fantastically as well! There were some really minor updates that I think could be made, but other than that, looks great to me!

2024-10-20 23:46 UTC, thisjustin123 requested changes
Some small changes! Also, take a look at andrew's other comment about the header padding.

2024-10-20 23:46 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/uplift/ui/MainNavigationWrapper.kt
>          ) {
We should have a follow-up PR pretty soon about saving to local storage whether or not the user has already completed onboarding or not. It should be sufficient to just save this to local preferences and read it upon the app opening, changing the start destination accordingly.

2024-10-20 23:46 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/uplift/ui/screens/ProfileCreationScreen.kt
> +                )
Small nitpick, let's make these named arguments for readability (i.e. `paramName = arg`)

2024-10-20 23:48 UTC, thisjustin123 commented
> For the profile creation screen with the checkmarks, I think the current background is pinkish, so we might need to change background color. Also, it might be because of my emulator, but I think part of the "Complete your profile" title gets covered by the camera; not too sure how to fix though.

You should be able to fix this by using something like `Modifier.statusBarsPadding()`, but I'm not actually sure if this takes into account stuff like the camera... also, it doesn't even look like the status bars are there? It's worth a shot, but if that modifier doesn't work, there may be a similar one that'll give you the proper insets padding for the camera.

2024-12-03 01:55 UTC, AndrewCheung360 approved these changes

2024-12-03 15:39 UTC, thisjustin123 approved these changes

2025-01-29 21:44 UTC, merged